POST http://localhost:3003/api/blogs/
Content-Type: application/json

{   
   "title": "joke1",
   "author": "testAuthor",
   "url": "http://test/1",
   "likes": 30
}

###
GET http://localhost:3003/api/blogs/

###
DELETE http://localhost:3003/api/blogs/60983711639a285a00e9feda

###
PUT http://localhost:3003/api/blogs/60983709639a285a00e9fed9
Content-Type: application/json

{   
   "title": "joke3",
   "author": "testAuthor",
   "url": "http://test/3",
   "likes": 146
}